POST http://localhost:3000/mindreveal/api/v1/login
Content-Type: application/json

{
    "username": "ayaragab2",
    "password": "1234@@@wsAa"
}

###

GET http://localhost:3000/mindreveal/api/v1/thoughts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjoiMDM4ZDlkZjFkY2IxZWFhMDE3Y2QzMDFkYjA5ZDE1Yzc6ZmVkY2M3MjNiMzQyOTljMzE5ZjU2OTRkMzI1NWQ2NTNkZGEzZDRjZDA1MTU5YjAwNzJlNjYzNDI0ODZjMjhlNGZhMmI0YzVhYWU3ZmFlYjIzMDFlNGFiYjkxMzVhYjUzIiwiaWF0IjoxNzQ2NTQwODQ0LCJleHAiOjE3NDY2MjcyNDR9.ewfhWBu3Eozs7S_XRlJyI2YnBhkK_s_sghs0tRaQvdo
###

###
POST http://localhost:3000/mindreveal/api/v1/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjoiYzRlMDVlMDM5NzBmYzQ4MWU0ZjU4ODc0NzhkZDc4NWM6NGI4NzlkYWMyNjVjM2ViMDhjNDhiZTFlMTNiMDNjMjg4YTE2MTI5NjA2OGQzMzcwNTQ2ZGQ1YWQ5OTY2ZmI4ZGYzMjNmZTliMzI2M2M0NjE2Yjk1NWVlYjdhYzAwOTM1IiwiaWF0IjoxNzQ2NTE5MDY3LCJleHAiOjE3NDY1MTkwODJ9.0H3XKBFCZMgsb3maFwJcqEZjQ3m4e91wWrONo4l4yWQ


{
    "role": "admin"
}
###

POST http://localhost:3000/mindreveal/api/v1/token
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjoiNTMxMmQ1YjQwNTNhNjA3YzgzZDViODBkYjViMTQ2ZjY6ZTNlN2NiNDc0YjM0NTEwN2Y3ZjI4ZDkxYzI0YzMzNThkOWQ5YzI5ODE4ZjYzMmNhYmNlZjdlYThiMWQ5NjViNjdmMWUwY2RhODEwMWIzNGYyODdjMWMyYjU1ZGE2YzFkIiwiaWF0IjoxNzQ1ODIzMzkzLCJleHAiOjE3NDU4MjM0MDh9.EQefoJj5X_ULplW03ZnbrLW1OGb04nqCzXmWv67qCH8

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjoiMGUyYWIyOGZjMWQxYTYyOGFkMDc1NTNlNDNmOTUwODA6M2UyM2ZmYTk2MjFmNDYxZDkzODBhYWIyM2IwYTE4NjU4ZWYyZDZhNTZlMGUxNjdmOGUwNjI3ZTVhYjU0YjMwZWVmYzMyZmVlYjIxNDU5Y2E0ZDhjMGVmODgxNWEyYzA2IiwiaWF0IjoxNzQ1ODIzMzkzfQ.RzZjAdMk7BD-VX8969JEldq9eQG7inThuCExVF81zFE"
}