POST http://localhost:3000/mindreveal/api/v1/login
Content-Type: application/json

{
    "username": "admin.Ayaa3",
    "password": "123aaaAA@"
}

###

GET http://localhost:3000/mindreveal/api/v1/thoughts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjoiYWViNmVmNDNkZGZkMzY1MDdlMmZiYTQ0YzY3NTc1Yjc6OTdjMWFkZTkzZTcxMjFmY2ZjNzcyY2U2Yzc3ODk2MzcwNWZiY2EyNTdlYmE0YWI2NTRmNzUyOTRhMmU1MTc1ZWJmN2JhNjhmZmFlOWQ2NmJiODlkNzg4MTE2MDhmODExIiwiaWF0IjoxNzQ1NTgzNzc5LCJleHAiOjE3NDU1ODM3OTR9.1gGYf8ZWoAazOsz8pwNK6OVpFwKapDf2Eg2A_KOpTl8
###


POST http://localhost:3000/mindreveal/api/v1/token
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjoiNDYxNjExMjkzZDY2OTQzYmMzMjRmZjc3N2YyYzljMzc6YTc5Y2IzMjRmYTZmMzIxNzhmNDkzNTZiYjdiMDkwMjQ0NDg5ZDRkZTNhMzRlMGJiZDk0MGJkMGJhNDE2OWE5MTRhYWVkY2RkYzM5MGE3NGJiNDEzOGY3YjI0NDZhMGM5IiwiaWF0IjoxNzQ1NTgzNzc5fQ.uKOQCeMb9dI_HbvlpMZ8PUqg2Kulpm-HiPhswRgR4RU",
    "role": "admin"
}